app = "homeland-rp-bot-still-snowflake-8357"

primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[deploy]
  strategy = "immediate"

[processes]
  app = "python main.py"
