app = "homeland-rp-bot"  # Cambia si ya tienes otro

primary_region = "iad"  # Puedes cambiar la región

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"  # Esta sí puede quedarse

[processes]
  app = "python main.py"

[deploy]
  strategy = "immediate"
